---
- name: install mongodb
  hosts: all
  become: true
  tasks:
  - name: apt-get update
    apt:
      update_cache: yes

  - name: Install needed apps
    apt: "name={{ item }} state=present"
    with_items:
      - python
      - git

  - name: Add APT key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.2.asc
      state: present

  - name: adding repo
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present

  - name: install app
    apt:
      name: mongodb-org
      state: present

  - name: enable mongod
    systemd:
      name: mongod
      enabled: yes
