---
- name: installing apps
  hosts: all
  become: true
  tasks:
  - name: apt-get update
    apt:
      update_cache: yes
  - name: Install needed apps
    apt: "name={{ item }} state=present"
    with_items:
      - python
      - git
      - ruby-full
      - ruby-bundler
      - build-essential
