---
- name: Configure db host
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Install dependecies
      apt:
        pkg:
          - git
          - python
        state: present
    - name: mongodb config file
      template:
        src: "templates/mongod.conf.j2"
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod
  handlers:
    - name: restart mongod
      service: name=mongod state=restarted

- name: configure app host
  hosts: app
  become: true
  tags: app-tag
  vars:
    db_host: 192.168.10.3
  tasks:
    - name: check and install dependecies
      apt:
        pkg:
          - git
          - python
      state: present
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted


- name: deploy app
  hosts: app
  become: true
  vars:
    db_host: 192.168.10.3
  tags: deploy-tag
  tasks:

    - name: fetch last version of app code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma
    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      notify: reload puma
  handlers:
  - name: reload puma
    service: name=puma state=restarted
