---
- name: Configure hosts and deploy my app
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 192.168.10.16
  tasks:
    - name: Install dependecies
      become: true
      apt:
        pkg:
          - git
          - python
        state: present
      tags:
        - app-tag
        - db-tag
        - deploy-tag
    - name: mongodb config file
      become: true
      template:
        src: "templates/mongod.conf.j2"
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: add config file for db connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      notify: reload puma
      tags: app-tag
    - name: add service file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma
    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
    - name: fetch last version of app code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma
    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
        tags: deploy-tag
      notify: reload puma
  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
  - name: reload puma
    become: true
    service: name=puma state=restarted
